### ISSUE TITLE
No chosen multiple select widget

### ISSUE THREAD

**Issue by geohuz** [Kotti/deform_bootstrap#45]
There is no demo for chosen multiple select widget

**Comment by tisdall** [comment]
If you run the demo and go to /chosen_multiple or /chosen_single you will see the demo for chosen.  However, for some reason, those demos aren't listed in the menu unless you are already viewing them.  They also don't seem to render properly for me in Chrome.  (they're stuck in an iframe that's too short)

EDIT:  the issue with rendering is that it's in a div with `overflow:auto`.  I'm sure that's there for some reason, but it breaks the display of the chosen widgets.

**Comment by tonthon** [comment]
To get the chosen version packed with deform_bootstrap work well with chrome, I needed to add the following :

``` css
.chzn-container .chzn-results { margin-left: -5px; }
.chzn-container .chzn-results { clear: both; }
```
